### ISSUE TITLE
Update nadac price for non capsules and tablets to be by unit, not milliliters or other

### ISSUE THREAD

**Issue by akircher** [dscsa/client#134]

**Comment by akircher** [comment]
More generally, if someone manually updates an incorrect price, do we override it with a new update or keep it forever?  Can we programmatically fix incorrect prices?

**Comment by akircher** [comment]
Related to #34

**Comment by akircher** [comment]
Related to #164

**Comment by owsow** [comment]
What if we modified the update method, more generally, to consider the change it's about to make and see if it's reasonable, within some measure? Could it look at the old price (which may or may not have been manually edited) and the new price it found (which may be totally wrong) and if there's some crazy ratio or difference between the two, that's probably because this was manually updated from an incorrect value, so it leaves it alone. Based off the assumption that the prices aren't regularly going to actually change that much? Also, if the pricing data eventually improves, then it'll correct itself here.

**Comment by owsow** [comment]
I see. I checked the response from NADAC and GoodRx. NADAC gives a field called "pricing_unit" which I've so far seen as either "EA" or "ML". I'm assuming "EA" means each, so it would be per unit as opposed to milliliters, and we can check for that. GoodRx doesn't seem to have a similar field, but it does have a "quantity" field and for injections it seems to usually be one, so they're giving us data in unit-of-use and we'd need to manipulate the price knowing the strength.

**Comment by akircher** [comment]
In the NADAC response could we do a REGEX like /\/\d*ml/ to search for the # of milliliters in the denominator and if the units is expressed in ML then we multiply the price by what the regex finds.  Maybe that will give us all prices in units?

If that does not work or is error prone, maybe we talk about keeping everything in milliliters.  However then we have to convert goodrx to milliliters which will likely be even harder.

Adam

**Comment by owsow** [comment]
Submitted pull request with functionality that does that. Can continue to evaluate whether that totally solves the more general issue.
