### ISSUE TITLE
Create migration spreadsheet for inventory

### ISSUE THREAD

**Issue by akircher** [dscsa/client#181]
See https://docs.google.com/spreadsheets/d/1fXjHuXowYSdSAzQEh39FTXi33pR0CDLQ_h4bgDLdWdA/edit#gid=1144183694 for examples

**Comment by akircher** [comment]
We need to make sure to switch qty.from to qty.to and exp.from to exp.to

**Comment by owsow** [comment]
This is the process I put together. Rather long, but since this doesn't seem like a super frequent task, don't feel that optimizing it would be time well spent right now.

1. Copy-paste the inventory csv into the Migration Spreadsheet's first sheet. Adjust the limits of the bounds on the second sheet to include all rows at the bottom.
2. Export the second sheet as a csv.
3. Open in excel.
4. Create a second sheet, copy paste in the columns of exceptions and their correct versions.
5. Copy the NDC column into second sheet, use VLOOKUP and IFERROR to create a new column with all correct NDCs. Paste back into original sheet.
6. Make manual corrections:
    a. Switch qty.to and qty.from, as well as exp.to and exp.from
    b. Set the shipment._id to that of the user uploading.
    c. Set the verifiedAt field to have the current date in all the transaction rows.
